{
  "version": "V4.0.1 Governance",
  "registry": {
    "APP-00": "App Shell",
    "TOP-00": "Top Controls",
    "TOP-01": "Filter Button",
    "TOP-02": "Kartenmodus Button",
    "TOP-03": "Einstellungen Button",
    "TOP-04": "Audit Button",
    "NAV-00": "Bottom Navigation",
    "NAV-01": "Journal Tab",
    "NAV-02": "Karte Tab",
    "NAV-03": "Reise Tab",
    "NAV-04": "Dashboard Tab",
    "J-00": "Journal Ansicht",
    "J-01": "Journal Suche",
    "J-02": "Journal Filter Chip",
    "J-03": "PR-Zeile",
    "M-00": "Leaflet Karte",
    "M-01": "Basiskarten Umschaltung",
    "M-02": "PR-Pins",
    "M-03": "GPX Track Layer",
    "M-04": "KML Anfahrt Layer",
    "M-05": "Alle Pins Button",
    "PD-00": "PR Detailseite",
    "PD-01": "Detail Schließen",
    "PD-02": "Detail Kennwerte",
    "PD-03": "Detail Links",
    "PD-04": "GPX/KML Datenstatus",
    "F-00": "Filter Panel",
    "S-00": "Einstellungen Panel",
    "S-01": "Transparenz Regler",
    "R-00": "Reise Ansicht",
    "D-00": "Dashboard Ansicht",
    "A-00": "Audit Center",
    "A-01": "Audit Modus",
    "A-02": "Audit ID Labels",
    "A-03": "Notizmodus",
    "A-04": "Ticket Liste",
    "A-05": "CSV Export",
    "A-06": "JSON Export",
    "A-07": "CSV Import",
    "A-08": "Audit Notiz Popup"
  }
}
