(() => {
'use strict';
const PRX = { version:'V4.0 Baseline', data:null, map:null, layers:{pins:null,gpx:null,kml:null}, active:null, view:'journal', filter:{q:'',region:'',status:''}, baseLayers:{}, currentBase:null, settings:{sheetTransparency:.86, home:null} };
const $ = (s, r=document) => r.querySelector(s);
const el = (tag, cls, attrs={}) => { const n=document.createElement(tag); if(cls) n.className=cls; Object.entries(attrs).forEach(([k,v])=>{ if(k==='text') n.textContent=v; else if(k==='html') n.innerHTML=v; else if(k==='onclick') n.addEventListener('click',v); else n.setAttribute(k,v); }); return n; };
const Components = {
  iconButton(icon,label,onClick){ return el('button','icon-btn',{type:'button','aria-label':label,title:label,html:icon,onclick:onClick}); },
  closeButton(onClick){ return Components.iconButton('×','Schließen',onClick); },
  panel(title, body, onClose){ const p=el('section','panel'); const h=el('header','panel-header'); h.append(el('div','panel-title',{text:title}), Components.closeButton(onClose)); p.append(h, el('div','panel-body')); p.lastChild.append(body); return p; },
  navItem(id, icon, label){ return el('button','nav-item',{type:'button','data-view':id,html:`<span class="nav-ico">${icon}</span><span>${label}</span>`}); },
  kv(label,value){ const k=el('div','kv'); k.append(el('div','kv-label',{text:label}),el('div','kv-val',{text: value ?? 'Nicht in den bereitgestellten Daten vorhanden.'})); return k; },
  link(href, icon, label){ const a=el('a','link-btn',{href,target:'_blank',rel:'noopener'}); a.innerHTML=`<span>${icon}</span><span>${label}</span>`; return a; },
  toast(msg){ const t=$('#toast'); t.textContent=msg; t.hidden=false; clearTimeout(Components._toast); Components._toast=setTimeout(()=>t.hidden=true,2200); }
};
function fmt(v,s=''){ return v===null||v===undefined||v==='' ? '–' : `${v}${s}`; }
function safe(v){ return v===null||v===undefined||v==='' ? null : v; }
function statusIcon(s){ const x=(s||'').toLowerCase(); if(x.includes('offen')) return '●'; if(x.includes('geschlossen')) return '×'; if(x.includes('eingesch')) return '◐'; return '○'; }
async function init(){ renderChrome(); await loadData(); initMap(); renderView('journal'); renderPins(); }
async function loadData(){ try{ const res=await fetch('data/prs.json',{cache:'no-store'}); PRX.data=await res.json(); PRX.settings.home=PRX.data.meta.home; document.documentElement.style.setProperty('--sheetAlpha', PRX.settings.sheetTransparency); }catch(e){ PRX.data={meta:{counts:{}},prs:[]}; Components.toast('Daten konnten nicht geladen werden.'); console.error(e); } }
function renderChrome(){ const top=$('#topbar'); top.innerHTML=''; top.append(el('div','brand-pill',{html:'<span class="brand-dot"></span><span>PR-Explorer</span>'})); const actions=el('div','top-actions'); actions.append(Components.iconButton('⌕','Filter',openFilter), Components.iconButton('▣','Kartenmodus',()=>renderView('map')), Components.iconButton('⚙︎','Einstellungen',openSettings)); top.append(actions); const nav=$('#bottomNav'); nav.innerHTML=''; [['journal','☰','Journal'],['map','⌖','Karte'],['trip','◇','Reise'],['dashboard','▥','Dashboard']].forEach(n=>nav.append(Components.navItem(...n))); nav.addEventListener('click',e=>{ const b=e.target.closest('.nav-item'); if(b) renderView(b.dataset.view); }); }
function setNav(){ document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active', b.dataset.view===PRX.view)); }
function host(html=''){ const h=$('#viewHost'); h.innerHTML=html; return h; }
function renderView(v){ PRX.view=v; setNav(); host(); ['journal','map','trip','dashboard'].forEach(id=>{}); if(v==='journal') renderJournal(); if(v==='map') renderMapView(); if(v==='trip') renderTrip(); if(v==='dashboard') renderDashboard(); setTimeout(()=>PRX.map&&PRX.map.invalidateSize(),180); }
function filtered(){ let a=PRX.data.prs.slice(); const q=PRX.filter.q.toLowerCase(); if(q) a=a.filter(p=>`${p.id} ${p.name} ${p.region}`.toLowerCase().includes(q)); if(PRX.filter.region) a=a.filter(p=>p.region===PRX.filter.region); if(PRX.filter.status) a=a.filter(p=>(p.status||'prüfen')===PRX.filter.status); return a; }
function renderJournal(){ const h=host(); const v=el('section','view active list-shell'); const sp=el('div','scroll-pane'); sp.append(el('div','section-head',{html:`<h1 class="title">Journal</h1><div class="sub">${PRX.data.prs.length} PR-/PS-PR-Wege aus PR – V1.xlsx · Journal-first Baseline</div>`})); const tb=el('div','toolbar-row'); const inp=el('input','search',{placeholder:'Suche PR, Name, Region','aria-label':'Suche'}); inp.value=PRX.filter.q; inp.addEventListener('input',()=>{PRX.filter.q=inp.value; drawRows(list); renderPins();}); tb.append(inp, el('button','chip',{type:'button',text:'Filter',onclick:openFilter})); sp.append(tb); const list=el('div','flat-list'); sp.append(list); v.append(sp); h.append(v); drawRows(list); }
function drawRows(list){ list.innerHTML=''; const rows=filtered(); if(!rows.length){ list.append(el('div','empty',{text:'Keine PRs im aktuellen Filter.'})); return; } rows.forEach(p=>{ const b=el('button','pr-row',{type:'button',onclick:()=>openDetail(p.id)}); b.innerHTML=`<div class="status-dot">${statusIcon(p.status)}</div><div><div class="pr-title">${p.sourceNumber||p.id} · ${p.name}</div><div class="pr-meta"><span>${p.region}</span><span>${fmt(p.trail.distanceKm,' km')}</span><span>${fmt(p.trail.duration)}</span><span>${fmt(p.trail.elevGain,' hm')}</span></div></div><div class="pr-facts"><div>${fmt(p.drive.km,' km')}</div><div>${fmt(p.drive.min,' min')}</div></div>`; list.append(b); }); }
function renderMapView(){ const h=host(); const v=el('section','view active map-view'); const tools=el('div','map-tools'); ['OSM','Topo','Sat','Hybrid'].forEach(name=>tools.append(el('button','seg-btn',{type:'button',text:name,onclick:()=>setBase(name)}))); tools.append(el('button','seg-btn',{type:'button',text:'Alle Pins',onclick:()=>{PRX.active=null; clearActiveLines(); fitMadeira();}})); v.append(tools); h.append(v); }
function renderTrip(){ const h=host(); const v=el('section','view active list-shell'); const sp=el('div','scroll-pane'); sp.append(el('div','section-head',{html:'<h1 class="title">Reise</h1><div class="sub">V4.0 enthält bewusst nur die stabile Hülle. Tagesplanung folgt in V4.3.</div>'})); sp.append(el('div','dashboard-grid',{html:'<div class="metric"><div class="metric-num">14</div><div class="metric-label">Reisetage vorbereitet</div></div><div class="metric"><div class="metric-num">Home</div><div class="metric-label">Pestana Promenade Funchal</div></div>'})); sp.append(el('div','section-head',{html:'<div class="empty">Keine defekte Kalenderlogik. Später: einspaltige Tagesliste, Tagesdetail per Slide, PRs/POIs Heute/Später.</div>'})); v.append(sp); h.append(v); }
function renderDashboard(){ const c=PRX.data.meta.counts||{}; const h=host(); const v=el('section','view active list-shell'); const sp=el('div','scroll-pane'); sp.append(el('div','section-head',{html:`<h1 class="title">Dashboard</h1><div class="sub">Datenstatus · ${PRX.data.meta.version}</div>`})); sp.append(el('div','dashboard-grid',{html:`<div class="metric"><div class="metric-num">${c.prs||0}</div><div class="metric-label">PR-Stammdaten</div></div><div class="metric"><div class="metric-num">${c.gpxMatched||0}</div><div class="metric-label">GPX zugeordnet</div></div><div class="metric"><div class="metric-num">${c.kmlMatched||0}</div><div class="metric-label">KML zugeordnet</div></div><div class="metric"><div class="metric-num">0</div><div class="metric-label">Alt-Patches</div></div>`})); sp.append(el('div','section-head',{html:`<div class="empty">Quellen: ${PRX.data.meta.sourceFiles.join(' · ')}<br>Service Worker: nicht aktiv in V4.0.<br>Homezone: ${PRX.data.meta.home.name}</div>`})); v.append(sp); h.append(v); }
function initMap(){ if(!window.L){ Components.toast('Leaflet konnte nicht geladen werden.'); return; } PRX.map=L.map('map',{zoomControl:false,attributionControl:true}).setView([32.75,-16.95],10); PRX.baseLayers.OSM=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}); PRX.baseLayers.Topo=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'}); PRX.baseLayers.Sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}); PRX.baseLayers.Hybrid=L.layerGroup([PRX.baseLayers.Sat,L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{opacity:.34,maxZoom:19})]); setBase('OSM'); PRX.layers.pins=L.layerGroup().addTo(PRX.map); PRX.layers.gpx=L.layerGroup().addTo(PRX.map); PRX.layers.kml=L.layerGroup().addTo(PRX.map); L.control.zoom({position:'bottomright'}).addTo(PRX.map); setTimeout(()=>PRX.map.invalidateSize(),300); }
function setBase(name){ if(!PRX.map) return; if(PRX.currentBase) PRX.map.removeLayer(PRX.currentBase); PRX.currentBase=PRX.baseLayers[name]; PRX.currentBase.addTo(PRX.map); document.querySelectorAll('.seg-btn').forEach(b=>b.classList.toggle('active',b.textContent===name)); setTimeout(()=>PRX.map.invalidateSize(),100); }
function renderPins(){ if(!PRX.map||!PRX.layers.pins) return; PRX.layers.pins.clearLayers(); filtered().forEach(p=>{ if(!p.lat||!p.lon) return; const m=L.circleMarker([p.lat,p.lon],{radius:7,color:'#ffffff',weight:1,fillColor:'#38d5bd',fillOpacity:.9}); m.bindTooltip(`${p.sourceNumber||p.id} · ${p.name}`); m.on('click',()=>openDetail(p.id)); m.addTo(PRX.layers.pins); }); }
function fitMadeira(){ if(PRX.map) PRX.map.setView([32.75,-16.95],10); }
async function openDetail(id){ const p=PRX.data.prs.find(x=>x.id===id); if(!p) return; PRX.active=p; renderView('map'); await showActiveLines(p); if(PRX.map&&p.lat&&p.lon) PRX.map.setView([p.lat,p.lon],12); const host=$('#detailHost'); host.innerHTML=''; host.hidden=false; const sheet=el('section','detail-sheet'); const head=el('header','detail-header'); head.append(el('div','detail-title',{text:`${p.sourceNumber||p.id} · ${p.name}`}), Components.closeButton(()=>{host.hidden=true; clearActiveLines();})); const body=el('div','detail-body'); const grid=el('div','kv-grid'); [['Region',p.region],['Status',p.status],['Distanz',p.trail.distanceKm?`${p.trail.distanceKm} km`:null],['Dauer',p.trail.duration],['Höhenmeter',p.trail.elevGain?`${p.trail.elevGain} hm`:null],['Anfahrt',p.drive.min?`${p.drive.min} min · ${fmt(p.drive.km,' km')}`:null],['Höchster Punkt',p.trail.elevHigh?`${p.trail.elevHigh} m`:null],['Tiefster Punkt',p.trail.elevLow?`${p.trail.elevLow} m`:null]].forEach(x=>grid.append(Components.kv(x[0],x[1]))); body.append(grid, el('div','divider'));
 const links=el('div','link-grid'); if(p.googleMapsFromHome) links.append(Components.link(p.googleMapsFromHome,'⌖','Anfahrt')); if(p.links.visitMadeira) links.append(Components.link(`https://www.visitmadeira.com/de/resultate?Search=${encodeURIComponent(p.links.visitMadeira)}`,'↗','Visit')); if(p.lat&&p.lon) links.append(Components.link(`https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lon}`,'◎','Google')); body.append(links); body.append(el('div','divider'));
 body.append(el('div','empty',{html:`GPX: ${p.dataStatus.gpx?'vorhanden':'Nicht in den bereitgestellten Daten vorhanden.'}<br>KML: ${p.dataStatus.kml?'vorhanden':'Nicht in den bereitgestellten Daten vorhanden.'}<br>Parken/Gebühr: ${p.parking.info||p.parking.fee||'Nicht in den bereitgestellten Daten vorhanden.'}`})); sheet.append(head,body); host.append(sheet); }
async function showActiveLines(p){ clearActiveLines(); const bounds=[]; if(p.routeFile){ try{ const r=await (await fetch(p.routeFile)).json(); const line=L.polyline(r.points,{color:'#0a84ff',weight:5,opacity:.85}).addTo(PRX.layers.kml); bounds.push(...r.points); }catch(e){console.warn(e)} } if(p.trackFile){ try{ const g=await (await fetch(p.trackFile)).json(); const line=L.polyline(g.points,{color:'#ff453a',weight:5,opacity:.9}).addTo(PRX.layers.gpx); bounds.push(...g.points); }catch(e){console.warn(e)} } if(bounds.length&&PRX.map) PRX.map.fitBounds(bounds,{padding:[30,90],maxZoom:13}); }
function clearActiveLines(){ if(PRX.layers.gpx) PRX.layers.gpx.clearLayers(); if(PRX.layers.kml) PRX.layers.kml.clearLayers(); }
function openFilter(){ const body=el('div'); const regions=[...new Set(PRX.data.prs.map(p=>p.region).filter(Boolean))].sort(); const statuses=[...new Set(PRX.data.prs.map(p=>p.status||'prüfen'))].sort(); body.append(selectRow('Region',regions,PRX.filter.region,v=>{PRX.filter.region=v; renderPins(); if(PRX.view==='journal') renderJournal();}), selectRow('Status',statuses,PRX.filter.status,v=>{PRX.filter.status=v; renderPins(); if(PRX.view==='journal') renderJournal();}), el('button','chip',{type:'button',text:'Filter zurücksetzen',onclick:()=>{PRX.filter={q:'',region:'',status:''}; closePanel(); renderView('journal'); renderPins();}})); openPanel('Filter',body); }
function selectRow(label,items,value,onChange){ const row=el('div','settings-row'); row.append(el('div','kv-label',{text:label})); const s=el('select','search'); s.innerHTML='<option value="">Alle</option>'+items.map(i=>`<option ${i===value?'selected':''}>${i}</option>`).join(''); s.addEventListener('change',()=>onChange(s.value)); row.append(s); return row; }
function openSettings(){ const body=el('div'); body.append(el('div','empty',{html:`Version: ${PRX.version}<br>Homezone: ${PRX.settings.home.name}<br>${PRX.settings.home.lat}, ${PRX.settings.home.lon}`})); const row=el('div','settings-row'); row.append(el('div','kv-label',{text:'Transparenz'})); const range=el('input','',{type:'range',min:'60',max:'96',value:String(Math.round(PRX.settings.sheetTransparency*100))}); range.addEventListener('input',()=>{PRX.settings.sheetTransparency=Number(range.value)/100; document.documentElement.style.setProperty('--sheetAlpha', PRX.settings.sheetTransparency);}); row.append(range); body.append(row); openPanel('Einstellungen',body); }
function openPanel(title,body){ const host=$('#panelHost'); host.innerHTML=''; host.hidden=false; host.append(Components.panel(title,body,closePanel)); }
function closePanel(){ const host=$('#panelHost'); host.hidden=true; host.innerHTML=''; }
window.addEventListener('resize',()=>setTimeout(()=>PRX.map&&PRX.map.invalidateSize(),120)); document.addEventListener('DOMContentLoaded',init);
})();
